export const terminology = {
  app: {
    title: 'UIE ERP',
    description: 'Unique Infra ERP web application.',
  },
  home: {
    heading: 'Unique Infra ERP',
    intro: 'Monorepo scaffold health check for the web and API applications.',
    serverSectionTitle: 'Server-side health',
    serverSectionHint: 'Fetched on the server directly from the API base URL.',
    clientSectionTitle: 'Client-side health',
    clientSectionHint: 'Fetched through the Next.js rewrite at /api/health.',
  },
  login: {
    heading: 'Sign in',
    loginId: 'Login ID',
    password: 'Password',
  },
  nav: {
    home: 'Home',
    purchase: 'Purchase',
    indents: 'Indents',
    enquiries: 'Enquiries',
    quotations: 'Quotations',
    comparisons: 'Comparisons',
    purchaseOrders: 'Purchase Orders',
    stores: 'Stores',
    goodsReceipts: 'Goods Receipts',
    qualityCheck: 'Quality Check',
    stock: 'Stock',
    materialIssues: 'Material Issues',
    rejectedMaterialReturns: 'Rejected Material Returns',
    planning: 'Planning',
    wbs: 'WBS',
    masters: 'Masters',
    companies: 'Companies',
    projects: 'Projects',
    sitesAndStores: 'Sites & Stores',
    items: 'Items',
    vendors: 'Vendors',
    administration: 'Administration',
    users: 'Users',
    rolesAndPermissions: 'Roles & Permissions',
    approvalMatrix: 'Approval Matrix',
    numberSeries: 'Number Series',
    auditLog: 'Audit Log',
    systemHealth: 'System Health',
    componentGallery: 'Component Gallery',
  },
  fields: {
    status: 'Status',
    service: 'Service',
    version: 'Version',
    time: 'Time',
    dateFormat: 'DD-MM-YYYY',
  },
  actions: {
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    filter: 'Filter',
    reset: 'Reset',
    export: 'Export',
    import: 'Import',
    actions: 'Actions',
    back: 'Back',
    confirm: 'Confirm',
    retry: 'Retry',
    close: 'Close',
    checkHealth: 'Check API health',
    checking: 'Checking...',
  },
  labels: {
    active: 'Active',
    inactive: 'Inactive',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    noData: 'No data',
    requiredMark: '*',
  },
  table: {
    columns: 'Columns',
    rowsPerPage: 'Rows per page',
    page: 'Page',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    clearSort: 'Clear sort',
  },
  filters: {
    title: 'Filters',
    reset: 'Reset',
    all: 'All',
  },
  forms: {
    unsavedChanges: 'You have unsaved changes. Leave this page?',
  },
  combobox: {
    searchPlaceholder: 'Search...',
    empty: 'No results found.',
  },
  validation: {
    required: 'This field is required.',
    invalidQuantity: 'Enter a valid quantity.',
  },
  gallery: {
    description: 'Every shared component rendered with sample data.',
    density: 'Density',
    comfortable: 'Comfortable',
    compact: 'Compact',
    sectionStatus: 'Status chip',
    sectionKeyValue: 'Key/value grid',
    sectionFeedback: 'Feedback states',
    sectionDialog: 'Confirm dialog',
    sectionToast: 'Toasts',
    sectionTable: 'Data table',
    sectionFilters: 'Filter bar',
    sectionForm: 'Form layout and fields',
    sectionDetail: 'Detail layout',
    openDialog: 'Open dialog',
    showSuccess: 'Show success toast',
    showError: 'Show error toast',
    showInfo: 'Show info toast',
    toastSuccess: 'Saved successfully.',
    toastError: 'Could not save.',
    toastInfo: 'Information message.',
  },
  statuses: {
    draft: 'Draft',
    submitted: 'Submitted',
    pendingApproval: 'Pending approval',
    approved: 'Approved',
    rejected: 'Rejected',
    returned: 'Returned',
    revised: 'Revised',
    cancelled: 'Cancelled',
    closed: 'Closed',
  },
  shell: {
    signOut: 'Sign out',
    profile: 'Profile',
    selectCompany: 'Select company',
    selectProject: 'Select project',
    notifications: 'Notifications',
  },
  messages: {
    screenPendingSpecification: 'Screen pending specification',
    notAuthorised: 'Not authorised',
    genericError: 'Something went wrong.',
    serverUnavailable: 'The API health endpoint could not be reached from the server.',
    clientIdle: 'Press the button to call /api/health through the web rewrite.',
    clientSuccess: 'The rewrite to the API succeeded.',
    clientError: 'The API health endpoint could not be reached from the browser.',
  },
} as const;

export type Terminology = typeof terminology;
