export const terminology = {
  app: {
    title: 'UIE ERP',
    description: 'Unique Infra ERP web application.',
  },
  home: {
    heading: 'Unique Infra ERP',
    intro: 'Monorepo scaffold health check for the web and API applications.',
    serverSectionTitle: 'Server-side health',
    serverSectionHint: 'Fetched on the server directly from the API base URL.',
    clientSectionTitle: 'Client-side health',
    clientSectionHint: 'Fetched through the Next.js rewrite at /api/health.',
  },
  login: {
    heading: 'Sign in',
    loginId: 'Employee code / Username or Email',
    password: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in...',
    invalidCredentials: 'The employee code, username, email or password is incorrect.',
    accountLocked:
      'This account is temporarily locked. Try again in 15 minutes or contact an administrator.',
    rateLimited: 'Too many sign-in attempts. Please wait a minute and try again.',
    genericError: 'Could not sign in. Please try again.',
  },
  account: {
    changePasswordTitle: 'Change password',
    changePasswordRequired: 'You must change your password before you continue.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordPolicy: 'At least 8 characters, with at least one letter and one digit.',
    passwordChanged: 'Password changed.',
    invalidCurrentPassword: 'The current password is incorrect.',
    changePasswordError: 'Could not change the password. Please try again.',
    logoutError: 'Could not sign out. Please try again.',
  },
  nav: {
    home: 'Home',
    purchase: 'Purchase',
    indents: 'Indents',
    enquiries: 'Enquiries',
    quotations: 'Quotations',
    comparisons: 'Comparisons',
    purchaseOrders: 'Purchase Orders',
    stores: 'Stores',
    goodsReceipts: 'Goods Receipts',
    qualityCheck: 'Quality Check',
    stock: 'Stock',
    materialIssues: 'Material Issues',
    rejectedMaterialReturns: 'Rejected Material Returns',
    planning: 'Planning',
    wbs: 'WBS',
    masters: 'Masters',
    companies: 'Companies',
    projects: 'Projects',
    sitesAndStores: 'Sites & Stores',
    items: 'Items',
    vendors: 'Vendors',
    administration: 'Administration',
    users: 'Users',
    rolesAndPermissions: 'Roles & Permissions',
    approvalMatrix: 'Approval Matrix',
    numberSeries: 'Number Series',
    auditLog: 'Audit Log',
    systemHealth: 'System Health',
    componentGallery: 'Component Gallery',
  },
  fields: {
    status: 'Status',
    service: 'Service',
    version: 'Version',
    time: 'Time',
    dateFormat: 'DD-MM-YYYY',
  },
  actions: {
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    filter: 'Filter',
    reset: 'Reset',
    export: 'Export',
    import: 'Import',
    actions: 'Actions',
    back: 'Back',
    confirm: 'Confirm',
    retry: 'Retry',
    close: 'Close',
    checkHealth: 'Check API health',
    checking: 'Checking...',
  },
  labels: {
    active: 'Active',
    inactive: 'Inactive',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    noData: 'No data',
    requiredMark: '*',
  },
  table: {
    columns: 'Columns',
    rowsPerPage: 'Rows per page',
    page: 'Page',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    clearSort: 'Clear sort',
  },
  filters: {
    title: 'Filters',
    reset: 'Reset',
    all: 'All',
  },
  forms: {
    unsavedChanges: 'You have unsaved changes. Leave this page?',
  },
  combobox: {
    searchPlaceholder: 'Search...',
    empty: 'No results found.',
  },
  validation: {
    required: 'This field is required.',
    invalidQuantity: 'Enter a valid quantity.',
    passwordTooShort: 'Use at least 8 characters.',
    passwordNeedsLetter: 'Include at least one letter.',
    passwordNeedsDigit: 'Include at least one digit.',
    passwordMismatch: 'The passwords do not match.',
    invalidEmail: 'Enter a valid email address.',
    invalidRoleCode:
      'Use capital letters, digits and underscores, starting with a letter (for example STORE_KEEPER).',
  },
  users: {
    subtitle: 'People who can sign in to the ERP.',
    newUser: 'New user',
    editUser: 'Edit user',
    searchLabel: 'Search by username, email or name',
    statusFilter: 'Status',
    columnUsername: 'Username',
    columnDisplayName: 'Display name',
    columnEmail: 'Email',
    columnRoles: 'Roles',
    columnStatus: 'Status',
    columnLastLogin: 'Last sign-in',
    fieldUsername: 'Employee code / Username',
    fieldEmail: 'Email',
    fieldDisplayName: 'Display name',
    fieldActive: 'Active',
    fieldRoles: 'Roles',
    fieldTemporaryPassword: 'Temporary password',
    temporaryPasswordHint: 'The user must change it at the first sign-in.',
    sectionAccount: 'Account',
    sectionAccess: 'Access',
    sectionInfo: 'Sign-in information',
    infoLastLogin: 'Last sign-in',
    infoLockedUntil: 'Locked until',
    infoFailedLogins: 'Failed sign-in attempts',
    infoMustChangePassword: 'Must change password',
    infoCreated: 'Created',
    infoUpdated: 'Updated',
    never: 'Never',
    notLocked: 'Not locked',
    locked: 'Locked',
    noRoles: 'No roles',
    resetPassword: 'Reset password',
    resetDescription:
      'Set a temporary password. The user is signed out everywhere and must change it at the next sign-in.',
    unlock: 'Unlock',
    unlockTitle: 'Unlock account',
    unlockDescription: 'Clear the failed sign-in attempts and the lock on this account.',
    created: 'User created.',
    updated: 'User updated.',
    passwordReset: 'Password reset.',
    unlocked: 'Account unlocked.',
    loadError: 'Users could not be loaded.',
    notFound: 'User not found.',
    rolesUnavailable: 'Roles could not be loaded. The existing roles are kept unchanged.',
  },
  roles: {
    subtitle: 'Roles and the permissions they grant.',
    newRole: 'New role',
    editRole: 'Edit role',
    columnCode: 'Code',
    columnName: 'Name',
    columnType: 'Type',
    columnStatus: 'Status',
    columnUsers: 'Users',
    columnPermissions: 'Permissions',
    typeSystem: 'System',
    typeCustom: 'Custom',
    fieldCode: 'Code',
    fieldCodeHint: 'Capital letters, digits and underscores, for example STORE_KEEPER.',
    fieldName: 'Name',
    fieldActive: 'Active',
    sectionDetails: 'Role',
    sectionPermissions: 'Permissions',
    permissionsHint: 'Tick what this role may do on each screen.',
    systemRoleNotice: 'System role: its name, status and permissions cannot be changed.',
    created: 'Role created.',
    updated: 'Role updated.',
    loadError: 'Roles could not be loaded.',
    notFound: 'Role not found.',
    allPermissions: 'All permissions',
  },
  permissionActions: {
    view: 'View',
    manage: 'Manage',
  },
  apiErrors: {
    FORBIDDEN: 'You do not have permission to do this.',
    LAST_ADMINISTRATOR:
      'The last active administrator cannot be deactivated or lose the Administrator role.',
    CANNOT_DEACTIVATE_SELF: 'You cannot deactivate your own account.',
    DUPLICATE_USERNAME: 'This username is already in use.',
    DUPLICATE_EMAIL: 'This email is already in use.',
    DUPLICATE_ROLE_CODE: 'This role code is already in use.',
    SYSTEM_ROLE_PROTECTED:
      'System roles cannot be renamed, deactivated or have their permissions changed.',
    INVALID_ROLE: 'One or more selected roles no longer exist.',
    NOT_FOUND: 'The record no longer exists.',
    VALIDATION_ERROR: 'Some values are not valid. Check the form and try again.',
  },
  gallery: {
    description: 'Every shared component rendered with sample data.',
    density: 'Density',
    comfortable: 'Comfortable',
    compact: 'Compact',
    sectionStatus: 'Status chip',
    sectionKeyValue: 'Key/value grid',
    sectionFeedback: 'Feedback states',
    sectionDialog: 'Confirm dialog',
    sectionToast: 'Toasts',
    sectionTable: 'Data table',
    sectionFilters: 'Filter bar',
    sectionForm: 'Form layout and fields',
    sectionDetail: 'Detail layout',
    openDialog: 'Open dialog',
    showSuccess: 'Show success toast',
    showError: 'Show error toast',
    showInfo: 'Show info toast',
    toastSuccess: 'Saved successfully.',
    toastError: 'Could not save.',
    toastInfo: 'Information message.',
  },
  statuses: {
    draft: 'Draft',
    submitted: 'Submitted',
    pendingApproval: 'Pending approval',
    approved: 'Approved',
    rejected: 'Rejected',
    returned: 'Returned',
    revised: 'Revised',
    cancelled: 'Cancelled',
    closed: 'Closed',
  },
  shell: {
    signOut: 'Sign out',
    changePassword: 'Change password',
    profile: 'Profile',
    selectCompany: 'Select company',
    selectProject: 'Select project',
    notifications: 'Notifications',
  },
  messages: {
    screenPendingSpecification: 'Screen pending specification',
    notAuthorised: 'Not authorised',
    genericError: 'Something went wrong.',
    serverUnavailable: 'The API health endpoint could not be reached from the server.',
    clientIdle: 'Press the button to call /api/health through the web rewrite.',
    clientSuccess: 'The rewrite to the API succeeded.',
    clientError: 'The API health endpoint could not be reached from the browser.',
  },
} as const;

export type Terminology = typeof terminology;
