export const terminology = {
  app: {
    title: 'UIE ERP',
    description: 'Unique Infra ERP web application.',
  },
  home: {
    heading: 'Unique Infra ERP',
    intro: 'Monorepo scaffold health check for the web and API applications.',
    serverSectionTitle: 'Server-side health',
    serverSectionHint: 'Fetched on the server directly from the API base URL.',
    clientSectionTitle: 'Client-side health',
    clientSectionHint: 'Fetched through the Next.js rewrite at /api/health.',
  },
  login: {
    heading: 'Sign in',
    loginId: 'Login ID',
    password: 'Password',
  },
  nav: {
    home: 'Home',
    purchase: 'Purchase',
    indents: 'Indents',
    enquiries: 'Enquiries',
    quotations: 'Quotations',
    comparisons: 'Comparisons',
    purchaseOrders: 'Purchase Orders',
    stores: 'Stores',
    goodsReceipts: 'Goods Receipts',
    qualityCheck: 'Quality Check',
    stock: 'Stock',
    materialIssues: 'Material Issues',
    rejectedMaterialReturns: 'Rejected Material Returns',
    planning: 'Planning',
    wbs: 'WBS',
    masters: 'Masters',
    companies: 'Companies',
    projects: 'Projects',
    sitesAndStores: 'Sites & Stores',
    items: 'Items',
    vendors: 'Vendors',
    administration: 'Administration',
    users: 'Users',
    rolesAndPermissions: 'Roles & Permissions',
    approvalMatrix: 'Approval Matrix',
    numberSeries: 'Number Series',
    auditLog: 'Audit Log',
    systemHealth: 'System Health',
    componentGallery: 'Component Gallery',
  },
  fields: {
    status: 'Status',
    service: 'Service',
    version: 'Version',
    time: 'Time',
  },
  actions: {
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    actions: 'Actions',
    back: 'Back',
    confirm: 'Confirm',
    retry: 'Retry',
    checkHealth: 'Check API health',
    checking: 'Checking...',
  },
  labels: {
    active: 'Active',
    inactive: 'Inactive',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    noData: 'No data',
  },
  statuses: {
    draft: 'Draft',
    submitted: 'Submitted',
    pendingApproval: 'Pending approval',
    approved: 'Approved',
    rejected: 'Rejected',
    returned: 'Returned',
    revised: 'Revised',
    cancelled: 'Cancelled',
    closed: 'Closed',
  },
  shell: {
    signOut: 'Sign out',
    profile: 'Profile',
    selectCompany: 'Select company',
    selectProject: 'Select project',
    notifications: 'Notifications',
  },
  messages: {
    screenPendingSpecification: 'Screen pending specification',
    notAuthorised: 'Not authorised',
    genericError: 'Something went wrong.',
    serverUnavailable: 'The API health endpoint could not be reached from the server.',
    clientIdle: 'Press the button to call /api/health through the web rewrite.',
    clientSuccess: 'The rewrite to the API succeeded.',
    clientError: 'The API health endpoint could not be reached from the browser.',
  },
} as const;

export type Terminology = typeof terminology;
