export const ALL_PERMISSIONS = [
  'purchase.indents.view',
  'purchase.enquiries.view',
  'purchase.quotations.view',
  'purchase.comparisons.view',
  'purchase.purchaseOrders.view',
  'stores.goodsReceipts.view',
  'stores.qualityCheck.view',
  'stores.stock.view',
  'stores.materialIssues.view',
  'stores.rejectedMaterialReturns.view',
  'planning.wbs.view',
  'masters.companies.view',
  'masters.projects.view',
  'masters.sitesAndStores.view',
  'masters.items.view',
  'masters.vendors.view',
  'administration.users.view',
  'administration.users.manage',
  'administration.rolesAndPermissions.view',
  'administration.rolesAndPermissions.manage',
  'administration.approvalMatrix.view',
  'administration.numberSeries.view',
  'administration.auditLog.view',
  'administration.systemHealth.view',
  'administration.componentGallery.view',
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];
